site_name: Greenmask

# Theme
theme:
  name: material
#  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.sections
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
#    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    scheme: default
    primary: teal
    accent: indigo
    toggle:
      icon: material/brightness-7




# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - tables

nav:
  - Home: index.md
  - Documentation:
      - Getting started: getting-started.md
      - Architecture: architecture.md
      - Installation: installation.md
      - Commands: commands.md
      - Configuration: configuration.md
      - Built-in transformers: built-in-transformers.md
      - Custom transformers: custom-transformers.md

repo_url: https://github.com/GreenmaskIO/greenmask
repo_name: GreenmaskIO/greenmask
site_url: https://greenmask.io
copyright: Copyright &copy; 2023 Greenmask


extra:
#    version:
  #    provider: mike
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/GreenmaskIO
    - icon: fontawesome/brands/discord
      link: https://discord.gg/97AKHdGD
    - icon: fontawesome/brands/github
      link: https://github.com/GreenmaskIO/greenmask

plugins:
  - social
  - search
